// <auto-generated />
using System;
using Gazelle.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gazelle.Migrations
{
    [DbContext(typeof(GazelleContext))]
    partial class GazelleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("Gazelle.Models.By", b =>
                {
                    b.Property<Guid>("ById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("ById");

                    b.ToTable("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
